export const metadata = {
    title: 'Create Next dashboard',
    description: 'Generated by create next app',
  }

export default function DashboardLayout({children}) {
  return (
    <html>
      <body>
        <div>DashboardLayout {children}</div>

      </body>
    </html>
  )
}
